# Generated by Django 5.2 on 2026-02-26 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_date', models.DateField(auto_created=True)),
                ('post_description', models.TextField(max_length=244)),
                ('poster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website_app.profile')),
            ],
        ),
    ]
